from .structures import Affix, SandhiPOS, LeftSandhi, RightSandhi, \
    ReplaceSandhi, GiJaqtuqSandhi, TeSandhi, GemSandhi, GeSandhi, UsiqSandhi, \
    KkuqSandhi, AqDropSandhi, SsaSandhi, WeakQStemSandhi, KStemSandhi, \
    WeakenableSandhi, PassPartSandhi, JuaqSandhi, TcTriggerSandhi, ActPartSandhi, \
    GinnaqSandhi, HTRSandhi, TDeletingSandhi, TTruncSandhi, LimitedGemSandhi

# TODO: metathesis of lək [currently gemination]
# TODO: since anything needs TcTrigger, why not write it to the general class RightSandhi?

affixes: list[Affix] = [
    Affix("utə", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=TeSandhi(pos=SandhiPOS.VERB)), 
    Affix("utə", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=TeSandhi(pos=SandhiPOS.NOUN)), 
    Affix("utə", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=TeSandhi(pos=SandhiPOS.VERB)), 
    Affix("irutə", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=TeSandhi(pos=SandhiPOS.VERB)), 
    Affix("niq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)), 
    Affix("tət", 
          left=TTruncSandhi(pos=SandhiPOS.VERB), 
          right=TcTriggerSandhi(pos=SandhiPOS.VERB)), 
    Affix("ði", 
          left=HTRSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),  # TODO: strange sandhi
    Affix("qatəgiik", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("qatəgə", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=GeSandhi(pos=SandhiPOS.VERB)),
    Affix("qatə", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=TeSandhi(pos=SandhiPOS.NOUN)),
    Affix("nqik", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("gi^jaqtuq", 
          left=GiJaqtuqSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("g^innaq", 
          left=GinnaqSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("g^innaq", 
          left=GinnaqSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=KStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("qqu", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("qqa", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),  # STATE -qqa- making stative verbs
    Affix("ŋŋit",
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=TcTriggerSandhi(pos=SandhiPOS.VERB)),
    Affix("yuma", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("yumaaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("yunnaaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("qaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("u", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True, weakening=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("gə", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=GeSandhi(pos=SandhiPOS.VERB)),
    Affix("təgə", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=GeSandhi(pos=SandhiPOS.VERB)),
    Affix("qə", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=GeSandhi(pos=SandhiPOS.VERB)),
    Affix("ssa", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=SsaSandhi(pos=SandhiPOS.VERB)),
    Affix("sima", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("vallaaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("tuq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("riaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("riassa", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=SsaSandhi(pos=SandhiPOS.VERB)),
    Affix("ðuq", 
          left=ActPartSandhi(pos=SandhiPOS.VERB), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("f^fik", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=KStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("sinnau", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("galuaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("galuaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=AqDropSandhi(pos=SandhiPOS.NOUN)),
    Affix("l^luaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=AqDropSandhi(pos=SandhiPOS.VERB)),
    Affix("gijaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=AqDropSandhi(pos=SandhiPOS.VERB)),
    Affix("ŋŋuaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=AqDropSandhi(pos=SandhiPOS.NOUN)),
    Affix("kcaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("ŋŋuq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("si", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("kkuq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=KkuqSandhi(pos=SandhiPOS.NOUN)),
    Affix("riiq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ccusiq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=UsiqSandhi(pos=SandhiPOS.NOUN)),
    Affix("nəq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=WeakenableSandhi(pos=SandhiPOS.NOUN)),
    Affix("nəqaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("suuq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("uq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("lək", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=LimitedGemSandhi(pos=SandhiPOS.NOUN)),
    Affix("ðuqaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("laaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("q^cuaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=AqDropSandhi(pos=SandhiPOS.NOUN)),
    Affix("q^vakcuaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=AqDropSandhi(pos=SandhiPOS.NOUN)),
    Affix("liq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("liq", 
          left=ReplaceSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("niaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ðarijaqaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("miuq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("ðaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ðaq", 
          left=PassPartSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("ðaqaq", 
          left=PassPartSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("taaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("taq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)), # member
    Affix("vik", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("vik", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.NOUN)),
    Affix("rujuk", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.NOUN)),
    Affix("liaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ðukcau", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("liuq", 
          left=ReplaceSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("siuq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ŋajak", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ŋajak", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.NOUN)),
    Affix("juaq", 
          left=JuaqSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("t^", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("lijaq", 
          left=ReplaceSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("kit", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=TcTriggerSandhi(pos=SandhiPOS.VERB)),
    Affix("jaaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("araq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=GemSandhi(pos=SandhiPOS.NOUN)),
    Affix("Vraq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=GemSandhi(pos=SandhiPOS.NOUN)),
    Affix("ŋaatciaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("ŋaaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("niraq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("tu", 
          left=LeftSandhi(pos=SandhiPOS.NOUN), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("gallaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("naviaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("qqajaa", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("nəqcaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=WeakQStemSandhi(pos=SandhiPOS.NOUN)),
    Affix("tuqaq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=GemSandhi(pos=SandhiPOS.NOUN)),
    Affix("q^gusuk", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("gi", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)), #TODO: strange metathesis sandhi
    Affix("gik", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("gunaq", 
          left=LeftSandhi(pos=SandhiPOS.VERB), 
          right=RightSandhi(pos=SandhiPOS.VERB)),
    Affix("minəq", 
          left=LeftSandhi(pos=SandhiPOS.NOUN, truncative=True), 
          right=WeakenableSandhi(pos=SandhiPOS.NOUN)),
]

affix_vn_dict: dict[SandhiPOS, list[Affix]] = {
    SandhiPOS.NOUN: [],
    SandhiPOS.VERB:[],
    None: affixes
}

for affix in affixes:
    affix_vn_dict[affix.left.pos].append(affix)

